# Generated by Django 4.2.3 on 2023-07-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_tag_product_price_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
    ]
