# Generated by Django 4.2.3 on 2023-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0004_remove_order_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='appstore.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
